/**
 * Comprehensive Bangladesh Location Data
 * 8 Divisions, 64 Districts with GPS Coordinates & Complete Upazila/Thana Mapping
 * Used for accurate astronomical prayer time calculation in BST (UTC+06:00)
 */

export interface LocationDivision {
  id: string;
  nameBn: string;
  nameEn: string;
}

export interface LocationDistrict {
  id: string;
  divisionId: string;
  nameBn: string;
  nameEn: string;
  lat: number;
  lng: number;
  offsetMins: number; // BST 90.0°E meridian longitude offset in minutes
  upazilas: string[];
}

export const BANGLADESH_DIVISIONS: LocationDivision[] = [
  { id: 'dhaka', nameBn: 'ঢাকা', nameEn: 'Dhaka' },
  { id: 'chattogram', nameBn: 'চট্টগ্রাম', nameEn: 'Chattogram' },
  { id: 'rajshahi', nameBn: 'রাজশাহী', nameEn: 'Rajshahi' },
  { id: 'khulna', nameBn: 'খুলনা', nameEn: 'Khulna' },
  { id: 'barishal', nameBn: 'বরিশাল', nameEn: 'Barishal' },
  { id: 'sylhet', nameBn: 'সিলেট', nameEn: 'Sylhet' },
  { id: 'rangpur', nameBn: 'রংপুর', nameEn: 'Rangpur' },
  { id: 'mymensingh', nameBn: 'ময়মনসিংহ', nameEn: 'Mymensingh' },
];

export const BANGLADESH_DISTRICTS_GEO: LocationDistrict[] = [
  // 1. ঢাকা বিভাগ (Dhaka Division - 13 Districts)
  {
    id: 'dhaka',
    divisionId: 'dhaka',
    nameBn: 'ঢাকা',
    nameEn: 'Dhaka',
    lat: 23.8103,
    lng: 90.4125,
    offsetMins: 0,
    upazilas: ['ধানমন্ডি', 'মিরপুর', 'গুলশান', 'উত্তরা', 'মতিঝিল', 'মোহাম্মদপুর', 'যাত্রাবাড়ী', 'বাড্ডা', 'তেজগাঁও', 'পল্টন', 'লালবাগ', 'সাভার', 'ধামরাই', 'কেরানীগঞ্জ', 'নবাবগঞ্জ', 'দোহার'],
  },
  {
    id: 'gazipur',
    divisionId: 'dhaka',
    nameBn: 'গাজীপুর',
    nameEn: 'Gazipur',
    lat: 24.0023,
    lng: 90.4264,
    offsetMins: 0,
    upazilas: ['গাজীপুর সদর', 'কালিয়াকৈর', 'শ্রীপুর', 'কাপাসিয়া', 'কালীগঞ্জ', 'টঙ্গী'],
  },
  {
    id: 'narayanganj',
    divisionId: 'dhaka',
    nameBn: 'নারায়ণগঞ্জ',
    nameEn: 'Narayanganj',
    lat: 23.6238,
    lng: 90.5000,
    offsetMins: 0,
    upazilas: ['নারায়ণগঞ্জ সদর', 'বন্দর', 'রূপগঞ্জ', 'সোনারগাঁও', 'আড়াইহাজার', 'সিদ্ধিরগঞ্জ'],
  },
  {
    id: 'tangail',
    divisionId: 'dhaka',
    nameBn: 'টাঙ্গাইল',
    nameEn: 'Tangail',
    lat: 24.2513,
    lng: 89.9167,
    offsetMins: 2,
    upazilas: ['টাঙ্গাইল সদর', 'মির্জাপুর', 'কালিহাতী', 'ঘাটাইল', 'সখিপুর', 'মধুপুর', 'নাগরপুর', 'দেলদুয়ার', 'গোপালপুর', 'ভূঞাপুর', 'বাসাইল', 'ধনবাড়ী'],
  },
  {
    id: 'manikganj',
    divisionId: 'dhaka',
    nameBn: 'মানিকগঞ্জ',
    nameEn: 'Manikganj',
    lat: 23.8644,
    lng: 90.0047,
    offsetMins: 1,
    upazilas: ['মানিকগঞ্জ সদর', 'সিংগাইর', 'শিবালয়', 'সাটুরিয়া', 'ঘিওর', 'দৌলতপুর', 'হরিরামপুর'],
  },
  {
    id: 'munshiganj',
    divisionId: 'dhaka',
    nameBn: 'মুন্সীগঞ্জ',
    nameEn: 'Munshiganj',
    lat: 23.5422,
    lng: 90.5305,
    offsetMins: 0,
    upazilas: ['মুন্সীগঞ্জ সদর', 'টংগিবাড়ী', 'সিরাজদিখান', 'লৌহজং', 'শ্রীনগর', 'গজারিয়া'],
  },
  {
    id: 'narsingdi',
    divisionId: 'dhaka',
    nameBn: 'নরসিংদী',
    nameEn: 'Narsingdi',
    lat: 23.9193,
    lng: 90.7202,
    offsetMins: -1,
    upazilas: ['নরসিংদী সদর', 'পলাশ', 'শিবপুর', 'রায়পুরা', 'বেলাব', 'মনোহরদী'],
  },
  {
    id: 'kishoreganj',
    divisionId: 'dhaka',
    nameBn: 'কিশোরগঞ্জ',
    nameEn: 'Kishoreganj',
    lat: 24.4449,
    lng: 90.7766,
    offsetMins: -1,
    upazilas: ['কিশোরগঞ্জ সদর', 'ভৈরব', 'বাজিতপুর', 'হোসেনপুর', 'করিমগঞ্জ', 'কটিয়াদী', 'কুলিয়ারচর', 'নিকলী', 'তাড়াইল', 'পাকুন্দিয়া', 'মিঠামইন', 'ইটনা', 'অষ্টগ্রাম'],
  },
  {
    id: 'faridpur',
    divisionId: 'dhaka',
    nameBn: 'ফরিদপুর',
    nameEn: 'Faridpur',
    lat: 23.6071,
    lng: 89.8429,
    offsetMins: 2,
    upazilas: ['ফরিদপুর সদর', 'বোয়ালমারী', 'মধুখালী', 'ভাঙ্গা', 'সালথা', 'নগরকান্দা', 'চরভদ্রাসন', 'সদরপুর', 'আলফাডাঙ্গা'],
  },
  {
    id: 'gopalganj',
    divisionId: 'dhaka',
    nameBn: 'গোপালগঞ্জ',
    nameEn: 'Gopalganj',
    lat: 23.0051,
    lng: 89.8266,
    offsetMins: 2,
    upazilas: ['গোপালগঞ্জ সদর', 'টুঙ্গিপাড়া', 'কোটালীপাড়া', 'মুকসুদপুর', 'কাশিয়ানী'],
  },
  {
    id: 'madaripur',
    divisionId: 'dhaka',
    nameBn: 'মাদারীপুর',
    nameEn: 'Madaripur',
    lat: 23.1641,
    lng: 90.1897,
    offsetMins: 1,
    upazilas: ['মাদারীপুর সদর', 'শিবচর', 'কালকিনি', 'রাজৈর', 'ডাসার'],
  },
  {
    id: 'rajbari',
    divisionId: 'dhaka',
    nameBn: 'রাজবাড়ী',
    nameEn: 'Rajbari',
    lat: 23.7574,
    lng: 89.6445,
    offsetMins: 3,
    upazilas: ['রাজবাড়ী সদর', 'পাংশা', 'বালিয়াকান্দি', 'গোয়ালন্দ', 'কালুখালী'],
  },
  {
    id: 'shariatpur',
    divisionId: 'dhaka',
    nameBn: 'শরীয়তপুর',
    nameEn: 'Shariatpur',
    lat: 23.2423,
    lng: 90.4348,
    offsetMins: 0,
    upazilas: ['শরীয়তপুর সদর', 'নড়িয়া', 'জাজিরা', 'ভেদরগঞ্জ', 'ডামুড্যা', 'গোসাইরহাট'],
  },

  // 2. চট্টগ্রাম বিভাগ (Chattogram Division - 11 Districts)
  {
    id: 'chattogram',
    divisionId: 'chattogram',
    nameBn: 'চট্টগ্রাম',
    nameEn: 'Chattogram',
    lat: 22.3569,
    lng: 91.7832,
    offsetMins: -5,
    upazilas: ['কোতোয়ালী', 'পাঁচলাইশ', 'পাহাড়তলী', 'হালিশহর', 'ডবলমুরিং', 'হরিণঘাটা', 'হাটহাজারী', 'রাউজান', 'রাঙ্গুনিয়া', 'ফটিকছড়ি', 'সীতাকুণ্ড', 'মীরসরাই', 'পটিয়া', 'বোয়ালখালী', 'আনোয়ারা', 'চন্দনাইশ', 'সাতকানিয়া', 'লোহাগাড়া', 'বাঁশখালী', 'সন্দ্বীপ', 'কর্ণফুলী'],
  },
  {
    id: 'coxsbazar',
    divisionId: 'chattogram',
    nameBn: 'কক্সবাজার',
    nameEn: "Cox's Bazar",
    lat: 21.4272,
    lng: 92.0058,
    offsetMins: -6,
    upazilas: ['কক্সবাজার সদর', 'চকরিয়া', 'পেকুয়া', 'মহেশখালী', 'কুতুবদিয়া', 'রামু', 'উখিয়া', 'টেকনাফ', 'ঈদগাঁও'],
  },
  {
    id: 'cumilla',
    divisionId: 'chattogram',
    nameBn: 'কুমিল্লা',
    nameEn: 'Cumilla',
    lat: 23.4607,
    lng: 91.1809,
    offsetMins: -3,
    upazilas: ['আদর্শ সদর', 'সদর দক্ষিণ', 'দাউদকান্দি', 'চান্দিনা', 'মুরাদনগর', 'দেবীদ্বার', 'হোমনা', 'তিতাস', 'মেঘনা', 'বুড়িচং', 'ব্রাহ্মণপাড়া', 'লাকসাম', 'বরুড়া', 'চৌদ্দগ্রাম', 'নাঙ্গলকোট', 'মনোহরগঞ্জ', 'লালমাই'],
  },
  {
    id: 'feni',
    divisionId: 'chattogram',
    nameBn: 'ফেনী',
    nameEn: 'Feni',
    lat: 23.0159,
    lng: 91.3976,
    offsetMins: -4,
    upazilas: ['ফেনী সদর', 'দাগনভূঞা', 'সোনাগাজী', 'ছাগলনাইয়া', 'পরশুরাম', 'ফুলগাজী'],
  },
  {
    id: 'brahmanbaria',
    divisionId: 'chattogram',
    nameBn: 'ব্রাহ্মণবাড়িয়া',
    nameEn: 'Brahmanbaria',
    lat: 23.9571,
    lng: 91.1119,
    offsetMins: -3,
    upazilas: ['ব্রাহ্মণবাড়িয়া সদর', 'আশুগঞ্জ', 'সরাইল', 'নাসিরনগর', 'নবীনগর', 'বাঞ্ছারামপুর', 'কসবা', 'আখাউড়া', 'বিজয়নগর'],
  },
  {
    id: 'noakhali',
    divisionId: 'chattogram',
    nameBn: 'নোয়াখালী',
    nameEn: 'Noakhali',
    lat: 22.8696,
    lng: 91.0998,
    offsetMins: -3,
    upazilas: ['নোয়াখালী সদর (সুধারাম)', 'বেগমগঞ্জ', 'চাটখিল', 'সেনবাগ', 'কোম্পানীগঞ্জ', 'হাতিয়া', 'কবিরহাট', 'সোনাইমুড়ী', 'সুবর্ণচর'],
  },
  {
    id: 'chandpur',
    divisionId: 'chattogram',
    nameBn: 'চাঁদপুর',
    nameEn: 'Chandpur',
    lat: 23.2333,
    lng: 90.6667,
    offsetMins: -1,
    upazilas: ['চাঁদপুর সদর', 'হাজীগঞ্জ', 'ফরিদগঞ্জ', 'মতলব উত্তর', 'মতলব দক্ষিণ', 'শাহরাস্তি', 'কচুয়া', 'হাইমচর'],
  },
  {
    id: 'lakshmipur',
    divisionId: 'chattogram',
    nameBn: 'লক্ষ্মীপুর',
    nameEn: 'Lakshmipur',
    lat: 22.9425,
    lng: 90.8412,
    offsetMins: -2,
    upazilas: ['লক্ষ্মীপুর সদর', 'রায়পুর', 'রামগঞ্জ', 'রামগতি', 'কমলনগর'],
  },
  {
    id: 'rangamati',
    divisionId: 'chattogram',
    nameBn: 'রাঙ্গামাটি',
    nameEn: 'Rangamati',
    lat: 22.7324,
    lng: 92.2985,
    offsetMins: -7,
    upazilas: ['রাঙ্গামাটি সদর', 'কাপ্তাই', 'কাউখালী', 'বাঘাইছড়ি', 'লংগদু', 'নানিয়ারচর', 'বরকল', 'জুরাইছড়ি', 'বিলাইছড়ি', 'রাজস্থলী'],
  },
  {
    id: 'khagrachhari',
    divisionId: 'chattogram',
    nameBn: 'খাগড়াছড়ি',
    nameEn: 'Khagrachhari',
    lat: 23.1193,
    lng: 91.9847,
    offsetMins: -6,
    upazilas: ['খাগড়াছড়ি সদর', 'দীঘিনালা', 'পানছড়ি', 'মহালছড়ি', 'মাটিরাঙ্গা', 'মানিকছড়ি', 'রামগড়', 'লক্ষ্মীছড়ি', 'গুইমারা'],
  },
  {
    id: 'bandarban',
    divisionId: 'chattogram',
    nameBn: 'বান্দরবান',
    nameEn: 'Bandarban',
    lat: 22.1953,
    lng: 92.2184,
    offsetMins: -7,
    upazilas: ['বান্দরবান সদর', 'রুমা', 'থানচি', 'রোয়াংছড়ি', 'লামা', 'আলীকদম', 'নাইক্ষ্যংছড়ি'],
  },

  // 3. সিলেট বিভাগ (Sylhet Division - 4 Districts)
  {
    id: 'sylhet',
    divisionId: 'sylhet',
    nameBn: 'সিলেট',
    nameEn: 'Sylhet',
    lat: 24.8949,
    lng: 91.8687,
    offsetMins: -6,
    upazilas: ['সিলেট সদর', 'দক্ষিণ সুরমা', 'গোলাপগঞ্জ', 'বিয়ানীবাজার', 'জকিগঞ্জ', 'কানাইঘাট', 'ফেঞ্চুগঞ্জ', 'বালাগঞ্জ', 'বিশ্বনাথ', 'কোম্পানীগঞ্জ', 'গোয়াইনঘাট', 'জৈন্তাপুর', 'ওসমানীনগর'],
  },
  {
    id: 'moulvibazar',
    divisionId: 'sylhet',
    nameBn: 'মৌলভীবাজার',
    nameEn: 'Moulvibazar',
    lat: 24.4829,
    lng: 91.7774,
    offsetMins: -5,
    upazilas: ['মৌলভীবাজার সদর', 'শ্রীমঙ্গল', 'কমলগঞ্জ', 'কুলাউড়া', 'বড়লেখা', 'রাজনগর', 'জুড়ী'],
  },
  {
    id: 'habiganj',
    divisionId: 'sylhet',
    nameBn: 'হবিগঞ্জ',
    nameEn: 'Habiganj',
    lat: 24.3749,
    lng: 91.4155,
    offsetMins: -4,
    upazilas: ['হবিগঞ্জ সদর', 'নবীগঞ্জ', 'বাহুবল', 'মাধবপুর', 'চুনারুঘাট', 'লাখাই', 'আজমিরীগঞ্জ', 'বানিয়াচং', 'শায়েস্তাগঞ্জ'],
  },
  {
    id: 'sunamganj',
    divisionId: 'sylhet',
    nameBn: 'সুনামগঞ্জ',
    nameEn: 'Sunamganj',
    lat: 25.0658,
    lng: 91.3950,
    offsetMins: -4,
    upazilas: ['সুনামগঞ্জ সদর', 'ছাতক', 'দোয়ারাবাজার', 'জগন্নাথপুর', 'দিরাই', 'শাল্লা', 'তাহিরপুর', 'ধর্মপাশা', 'জামালগঞ্জ', 'বিশ্বম্ভরপুর', 'মধ্যনগর', 'শান্তিগঞ্জ'],
  },

  // 4. রাজশাহী বিভাগ (Rajshahi Division - 8 Districts)
  {
    id: 'rajshahi',
    divisionId: 'rajshahi',
    nameBn: 'রাজশাহী',
    nameEn: 'Rajshahi',
    lat: 24.3636,
    lng: 88.6241,
    offsetMins: 7,
    upazilas: ['বোয়ালিয়া', 'রাজপাড়া', 'মতিহার', 'শাহ মখদুম', 'পবা', 'গোদাগাড়ী', 'তানোর', 'মোহনপুর', 'বাগমারা', 'দুর্গাপুর', 'পুঠিয়া', 'চারঘাট', 'বাঘা'],
  },
  {
    id: 'bogra',
    divisionId: 'rajshahi',
    nameBn: 'বগুড়া',
    nameEn: 'Bogura',
    lat: 24.8465,
    lng: 89.3777,
    offsetMins: 4,
    upazilas: ['বগুড়া সদর', 'শিবগঞ্জ', 'শেরপুর', 'ধুনট', 'গাবতলী', 'শাজাহানপুর', 'কাহালু', 'দুপচাঁচিয়া', 'আদমদীঘি', 'নন্দীগ্রাম', 'সারিয়াকান্দি', 'সোনাতলা'],
  },
  {
    id: 'pabna',
    divisionId: 'rajshahi',
    nameBn: 'পাবনা',
    nameEn: 'Pabna',
    lat: 24.0064,
    lng: 89.2372,
    offsetMins: 5,
    upazilas: ['পাবনা সদর', 'ঈশ্বরদী', 'সুজানগর', 'সাঁথিয়া', 'বেড়া', 'চাটমোহর', 'ফরিদপুর', 'ভাঙ্গুড়া', 'আটঘরিয়া'],
  },
  {
    id: 'sirajganj',
    divisionId: 'rajshahi',
    nameBn: 'সিরাজগঞ্জ',
    nameEn: 'Sirajganj',
    lat: 24.4534,
    lng: 89.7008,
    offsetMins: 3,
    upazilas: ['সিরাজগঞ্জ সদর', 'শাহজাদপুর', 'উল্লাপাড়া', 'বেলকুচি', 'কামারখন্দ', 'রায়গঞ্জ', 'তাড়াশ', 'কাজীপুর', 'চৌহালী'],
  },
  {
    id: 'naogaon',
    divisionId: 'rajshahi',
    nameBn: 'নওগাঁ',
    nameEn: 'Naogaon',
    lat: 24.7937,
    lng: 88.9318,
    offsetMins: 6,
    upazilas: ['নওগাঁ সদর', 'মহাদেবপুর', 'বদলগাছী', 'পত্নীতলা', 'ধামইরহাট', 'নিয়ামতপুর', 'মান্দা', 'আত্রাই', 'রাণীনগর', 'সাপাহার', 'পোরশা'],
  },
  {
    id: 'natore',
    divisionId: 'rajshahi',
    nameBn: 'নাটোর',
    nameEn: 'Natore',
    lat: 24.4206,
    lng: 88.9320,
    offsetMins: 6,
    upazilas: ['নাটোর সদর', 'সিংড়া', 'বড়াইগ্রাম', 'গুরুদাসপুর', 'লালপুর', 'বাগাতিপাড়া', 'নলডাঙ্গা'],
  },
  {
    id: 'chapainawabganj',
    divisionId: 'rajshahi',
    nameBn: 'চাঁপাইনবাবগঞ্জ',
    nameEn: 'Chapainawabganj',
    lat: 24.5965,
    lng: 88.2776,
    offsetMins: 8,
    upazilas: ['চাঁপাইনবাবগঞ্জ সদর', 'শিবগঞ্জ', 'গোমস্তাপুর', 'নাচোল', 'ভোলাহাট'],
  },
  {
    id: 'joypurhat',
    divisionId: 'rajshahi',
    nameBn: 'জয়পুরহাট',
    nameEn: 'Joypurhat',
    lat: 25.1015,
    lng: 89.0277,
    offsetMins: 5,
    upazilas: ['জয়পুরহাট সদর', 'পাঁচবিবি', 'কালাই', 'ক্ষেতলাল', 'আক্কেলপুর'],
  },

  // 5. খুলনা বিভাগ (Khulna Division - 10 Districts)
  {
    id: 'khulna',
    divisionId: 'khulna',
    nameBn: 'খুলনা',
    nameEn: 'Khulna',
    lat: 22.8456,
    lng: 89.5403,
    offsetMins: 4,
    upazilas: ['খুলনা সদর', 'সোনাডাঙ্গা', 'খালিশপুর', 'দৌলতপুর', 'খানজাহান আলী', 'বটিয়াঘাটা', 'ডুমুরিয়া', 'পাইকগাছা', 'কয়রা', 'রূপসা', 'তেরখাদা', 'দিঘলিয়া', 'ফুলতলা'],
  },
  {
    id: 'jessore',
    divisionId: 'khulna',
    nameBn: 'যশোর',
    nameEn: 'Jashore',
    lat: 23.1664,
    lng: 89.2081,
    offsetMins: 5,
    upazilas: ['যশোর সদর', 'ঝিকরগাছা', 'শার্শা', 'মণিরামপুর', 'কেশবপুর', 'অভয়নগর', 'বাঘারপাড়া', 'চৌগাছা'],
  },
  {
    id: 'satkhira',
    divisionId: 'khulna',
    nameBn: 'সাতক্ষীরা',
    nameEn: 'Satkhira',
    lat: 22.7185,
    lng: 89.0705,
    offsetMins: 5,
    upazilas: ['সাতক্ষীরা সদর', 'কলারোয়া', 'তালা', 'দেবহাটা', 'কালীগঞ্জ', 'আশাশুনি', 'শ্যামনগর'],
  },
  {
    id: 'kushtia',
    divisionId: 'khulna',
    nameBn: 'কুষ্টিয়া',
    nameEn: 'Kushtia',
    lat: 23.9013,
    lng: 89.1205,
    offsetMins: 5,
    upazilas: ['কুষ্টিয়া সদর', 'কুমারখালী', 'খোকসা', 'মিরপুর', 'ভেড়ামারা', 'দৌলতপুর'],
  },
  {
    id: 'jhenaidah',
    divisionId: 'khulna',
    nameBn: 'ঝিনাইদহ',
    nameEn: 'Jhenaidah',
    lat: 23.5450,
    lng: 89.1726,
    offsetMins: 5,
    upazilas: ['ঝিনাইদহ সদর', 'শৈলকুপা', 'হরিণাকুণ্ডু', 'কালীগঞ্জ', 'কোটচাঁদপুর', 'মহেশপুর'],
  },
  {
    id: 'chuadanga',
    divisionId: 'khulna',
    nameBn: 'চুয়াডাঙ্গা',
    nameEn: 'Chuadanga',
    lat: 23.6402,
    lng: 88.8418,
    offsetMins: 6,
    upazilas: ['চুয়াডাঙ্গা সদর', 'আলমডাঙ্গা', 'দামুড়হুদা', 'জীবননগর'],
  },
  {
    id: 'meherpur',
    divisionId: 'khulna',
    nameBn: 'মেহেরপুর',
    nameEn: 'Meherpur',
    lat: 23.7622,
    lng: 88.6318,
    offsetMins: 7,
    upazilas: ['মেহেরপুর সদর', 'গাংনী', 'মুজিবনগর'],
  },
  {
    id: 'bagerhat',
    divisionId: 'khulna',
    nameBn: 'বাগেরহাট',
    nameEn: 'Bagerhat',
    lat: 22.6516,
    lng: 89.7859,
    offsetMins: 3,
    upazilas: ['বাগেরহাট সদর', 'ফকিরহাট', 'মোল্লাহাট', 'কচুয়া', 'রামপাল', 'মোংলা', 'মোড়েলগঞ্জ', 'শরণখোলা', 'চিতলমারী'],
  },
  {
    id: 'narail',
    divisionId: 'khulna',
    nameBn: 'নড়াইল',
    nameEn: 'Narail',
    lat: 23.1725,
    lng: 89.5127,
    offsetMins: 4,
    upazilas: ['নড়াইল সদর', 'লোহাগড়া', 'কালিয়া'],
  },
  {
    id: 'magura',
    divisionId: 'khulna',
    nameBn: 'মাগুরা',
    nameEn: 'Magura',
    lat: 23.4873,
    lng: 89.4198,
    offsetMins: 4,
    upazilas: ['মাগুরা সদর', 'শ্রীপুর', 'মহম্মদপুর', 'শালিখা'],
  },

  // 6. বরিশাল বিভাগ (Barishal Division - 6 Districts)
  {
    id: 'barishal',
    divisionId: 'barishal',
    nameBn: 'বরিশাল',
    nameEn: 'Barishal',
    lat: 22.7010,
    lng: 90.3535,
    offsetMins: 0,
    upazilas: ['বরিশাল সদর (কোতোয়ালী)', 'বাকেরগঞ্জ', 'বাবুগঞ্জ', 'উজিরপুর', 'গৌরনদী', 'আগৈলঝাড়া', 'মেহেন্দিগঞ্জ', 'মুলাদী', 'হিজলা', 'বানারীপাড়া'],
  },
  {
    id: 'bhola',
    divisionId: 'barishal',
    nameBn: 'ভোলা',
    nameEn: 'Bhola',
    lat: 22.6859,
    lng: 90.6481,
    offsetMins: -1,
    upazilas: ['ভোলা সদর', 'দৌলতখান', 'বোরহানউদ্দিন', 'তজুমদ্দিন', 'লালমোহন', 'চরফ্যাশন', 'মনপুরা'],
  },
  {
    id: 'patuakhali',
    divisionId: 'barishal',
    nameBn: 'পটুয়াখালী',
    nameEn: 'Patuakhali',
    lat: 22.3596,
    lng: 90.3299,
    offsetMins: 0,
    upazilas: ['পটুয়াখালী সদর', 'বাউফল', 'গলাচিপা', 'দশমিনা', 'কলাপাড়া (কুয়াকাটা)', 'মির্জাগঞ্জ', 'দুমকি', 'রাঙ্গাবালী'],
  },
  {
    id: 'pirojpur',
    divisionId: 'barishal',
    nameBn: 'পিরোজপুর',
    nameEn: 'Pirojpur',
    lat: 22.5841,
    lng: 89.9720,
    offsetMins: 2,
    upazilas: ['পিরোজপুর সদর', 'ভাণ্ডারিয়া', 'মঠবাড়িয়া', 'নাজিরপুর', 'কাউখালী', 'নেছারাবাদ (স্বরূপকাঠি)', 'ইন্দুরকানী'],
  },
  {
    id: 'barguna',
    divisionId: 'barishal',
    nameBn: 'বরগুনা',
    nameEn: 'Barguna',
    lat: 22.0953,
    lng: 90.1121,
    offsetMins: 1,
    upazilas: ['বরগুনা সদর', 'আমতলী', 'পাথরঘাটা', 'বেতাগী', 'বামনা', 'তালতলী'],
  },
  {
    id: 'jhalokati',
    divisionId: 'barishal',
    nameBn: 'ঝালকাঠি',
    nameEn: 'Jhalokati',
    lat: 22.6406,
    lng: 90.1987,
    offsetMins: 1,
    upazilas: ['ঝালকাঠি সদর', 'নলছিটি', 'রাজাপুর', 'কাঁঠালিয়া'],
  },

  // 7. রংপুর বিভাগ (Rangpur Division - 8 Districts)
  {
    id: 'rangpur',
    divisionId: 'rangpur',
    nameBn: 'রংপুর',
    nameEn: 'Rangpur',
    lat: 25.7439,
    lng: 89.2752,
    offsetMins: 4,
    upazilas: ['রংপুর সদর', 'গঙ্গাচড়া', 'বদরগঞ্জ', 'কাউনিয়া', 'পীরগাছা', 'মিঠাপুকুর', 'পীরগঞ্জ', 'তারাগঞ্জ'],
  },
  {
    id: 'dinajpur',
    divisionId: 'rangpur',
    nameBn: 'দিনাজপুর',
    nameEn: 'Dinajpur',
    lat: 25.6217,
    lng: 88.6355,
    offsetMins: 7,
    upazilas: ['দিনাজপুর সদর', 'কাহারোল', 'বীরগঞ্জ', 'বোচাগঞ্জ', 'ফুলবাড়ী', 'পার্বতীপুর', 'নবাবগঞ্জ', 'ঘোড়াঘাট', 'হাকিমপুর (হিলি)', 'বিরামপুর', 'চিরিরবন্দর', 'খানসামা', 'বিরল'],
  },
  {
    id: 'gaibandha',
    divisionId: 'rangpur',
    nameBn: 'গাইবান্ধা',
    nameEn: 'Gaibandha',
    lat: 25.3288,
    lng: 89.5406,
    offsetMins: 3,
    upazilas: ['গাইবান্ধা সদর', 'গোবিন্দগঞ্জ', 'সুন্দরগঞ্জ', 'সাদুল্লাপুর', 'পলাশবাড়ী', 'সাঘাটা', 'ফুলছড়ি'],
  },
  {
    id: 'kurigram',
    divisionId: 'rangpur',
    nameBn: 'কুড়িগ্রাম',
    nameEn: 'Kurigram',
    lat: 25.8054,
    lng: 89.6362,
    offsetMins: 3,
    upazilas: ['কুড়িগ্রাম সদর', 'নাগেশ্বরী', 'ভূরুঙ্গামারী', 'ফুলবাড়ী', 'উলিপুর', 'চিলমারী', 'রৌমারী', 'রাজিবপুর', 'রাজারহাট'],
  },
  {
    id: 'lalmonirhat',
    divisionId: 'rangpur',
    nameBn: 'লালমনিরহাট',
    nameEn: 'Lalmonirhat',
    lat: 25.9923,
    lng: 89.2847,
    offsetMins: 4,
    upazilas: ['লালমনিরহাট সদর', 'হাতীবান্ধা', 'পাটগ্রাম', 'কালীগঞ্জ', 'আদিতমারী'],
  },
  {
    id: 'nilphamari',
    divisionId: 'rangpur',
    nameBn: 'নীলফামারী',
    nameEn: 'Nilphamari',
    lat: 25.9318,
    lng: 88.8560,
    offsetMins: 6,
    upazilas: ['নীলফামারী সদর', 'সৈয়দপুর', 'ডোমার', 'ডিমলা', 'জলঢাকা', 'কিশোরগঞ্জ'],
  },
  {
    id: 'panchagarh',
    divisionId: 'rangpur',
    nameBn: 'পঞ্চগড়',
    nameEn: 'Panchagarh',
    lat: 26.3411,
    lng: 88.5542,
    offsetMins: 7,
    upazilas: ['পঞ্চগড় সদর', 'তেঁতুলিয়া', 'দেবীগঞ্জ', 'বোদা', 'আটোয়ারী'],
  },
  {
    id: 'thakurgaon',
    divisionId: 'rangpur',
    nameBn: 'ঠাকুরগাঁও',
    nameEn: 'Thakurgaon',
    lat: 26.0337,
    lng: 88.4617,
    offsetMins: 8,
    upazilas: ['ঠাকুরগাঁও সদর', 'পীরগঞ্জ', 'রানীশংকৈল', 'বালিয়াডাঙ্গী', 'হরিপুর'],
  },

  // 8. ময়মনসিংহ বিভাগ (Mymensingh Division - 4 Districts)
  {
    id: 'mymensingh',
    divisionId: 'mymensingh',
    nameBn: 'ময়মনসিংহ',
    nameEn: 'Mymensingh',
    lat: 24.7471,
    lng: 90.4203,
    offsetMins: 0,
    upazilas: ['ময়মনসিংহ সদর', 'মুক্তাগাছা', 'ত্রিশাল', 'ভালুকা', 'গফরগাঁও', 'নান্দাইল', 'ঈশ্বরগঞ্জ', 'ফুলবাড়িয়া', 'ফুলপুর', 'তারাকান্দা', 'হালুয়াঘাট', 'ধোবাউড়া', 'গৌরীপুর'],
  },
  {
    id: 'jamalpur',
    divisionId: 'mymensingh',
    nameBn: 'জামালপুর',
    nameEn: 'Jamalpur',
    lat: 24.9375,
    lng: 89.9378,
    offsetMins: 2,
    upazilas: ['জামালপুর সদর', 'সরিষাবাড়ী', 'মেলান্দহ', 'ইসলামপুর', 'মাদারগঞ্জ', 'দেওয়ানগঞ্জ', 'বকশীগঞ্জ'],
  },
  {
    id: 'netrokona',
    divisionId: 'mymensingh',
    nameBn: 'নেত্রকোণা',
    nameEn: 'Netrokona',
    lat: 24.8709,
    lng: 90.7279,
    offsetMins: -1,
    upazilas: ['নেত্রকোণা সদর', 'কেন্দুয়া', 'মদন', 'মোহনগঞ্জ', 'খালিয়াজুড়ী', 'দুর্গাপুর', 'কলমাকান্দা', 'বারহাট্টা', 'পূর্বধলা', 'আটপাড়া'],
  },
  {
    id: 'sherpur',
    divisionId: 'mymensingh',
    nameBn: 'শেরপুর',
    nameEn: 'Sherpur',
    lat: 25.0205,
    lng: 90.0153,
    offsetMins: 2,
    upazilas: ['শেরপুর সদর', 'নকলা', 'নালিতাবাড়ী', 'শ্রীবরদী', 'ঝিনাইগাতী'],
  },
];

export const getDivisions = (): LocationDivision[] => BANGLADESH_DIVISIONS;

export const getDistrictsByDivision = (divisionIdOrName?: string): LocationDistrict[] => {
  if (!divisionIdOrName) return BANGLADESH_DISTRICTS_GEO;
  const clean = divisionIdOrName.trim().toLowerCase();
  const matchedDiv = BANGLADESH_DIVISIONS.find(
    d => d.id.toLowerCase() === clean || d.nameEn.toLowerCase() === clean || d.nameBn === divisionIdOrName.trim()
  );
  if (matchedDiv) {
    return BANGLADESH_DISTRICTS_GEO.filter(d => d.divisionId === matchedDiv.id);
  }
  return BANGLADESH_DISTRICTS_GEO.filter(d => d.divisionId === clean);
};

export const findDistrict = (districtNameOrId?: string): LocationDistrict => {
  if (!districtNameOrId) return BANGLADESH_DISTRICTS_GEO[0];
  const clean = districtNameOrId.trim().toLowerCase();
  const match = BANGLADESH_DISTRICTS_GEO.find(
    d =>
      d.id.toLowerCase() === clean ||
      d.nameEn.toLowerCase() === clean ||
      d.nameBn === districtNameOrId.trim() ||
      clean.includes(d.nameEn.toLowerCase()) ||
      districtNameOrId.includes(d.nameBn)
  );
  return match || BANGLADESH_DISTRICTS_GEO[0];
};

export const getUpazilasByDistrict = (districtNameOrId?: string): string[] => {
  const district = findDistrict(districtNameOrId);
  return district ? district.upazilas : [];
};
