/**
 * MASJIDLEDGER PRO v2.6 — POSTGRESQL AUXILIARY OPERATIONAL SCHEMA (PHASE 2)
 * Complete Relational Coverage for Auxiliary Domains A-G
 */

export const POSTGRES_AUXILIARY_SCHEMA_SQL = `
-- ============================================================================
-- DOMAIN A: LIBRARY & KNOWLEDGE CENTER
-- ============================================================================

CREATE TABLE IF NOT EXISTS library_categories (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(50) NOT NULL,
  description TEXT,
  parent_category_id VARCHAR(64),
  sort_order INT NOT NULL DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64),
  CONSTRAINT uq_lib_cat_mosque_code UNIQUE (mosque_id, code),
  CONSTRAINT uq_lib_cat_mosque_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS library_rooms (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  room_name VARCHAR(255) NOT NULL,
  room_code VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_lib_room_mosque_code UNIQUE (mosque_id, room_code),
  CONSTRAINT uq_lib_room_mosque_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS library_racks (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  room_id VARCHAR(64) NOT NULL,
  rack_name VARCHAR(255) NOT NULL,
  rack_code VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_lib_rack_mosque_code UNIQUE (mosque_id, rack_code),
  CONSTRAINT uq_lib_rack_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_lib_rack_room FOREIGN KEY (mosque_id, room_id) REFERENCES library_rooms(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS library_shelves (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  rack_id VARCHAR(64) NOT NULL,
  shelf_name VARCHAR(255) NOT NULL,
  shelf_code VARCHAR(50) NOT NULL,
  capacity INT DEFAULT 50,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_lib_shelf_mosque_code UNIQUE (mosque_id, shelf_code),
  CONSTRAINT uq_lib_shelf_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_lib_shelf_rack FOREIGN KEY (mosque_id, rack_id) REFERENCES library_racks(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_titles (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255),
  author VARCHAR(255) NOT NULL,
  translator VARCHAR(255),
  editor VARCHAR(255),
  publisher VARCHAR(255),
  publication_year INT,
  edition VARCHAR(50),
  language VARCHAR(32) NOT NULL DEFAULT 'BENGALI' CHECK (language IN ('BENGALI', 'ARABIC', 'URDU', 'ENGLISH', 'OTHER')),
  isbn VARCHAR(64),
  category_id VARCHAR(64) NOT NULL,
  category_name VARCHAR(255),
  subject VARCHAR(255),
  description TEXT,
  central_document_id VARCHAR(64),
  cover_image_url TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64),
  CONSTRAINT uq_book_title_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_book_title_category FOREIGN KEY (mosque_id, category_id) REFERENCES library_categories(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS library_members (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  person_id VARCHAR(64) NOT NULL,
  person_name VARCHAR(255),
  person_phone VARCHAR(32),
  member_code VARCHAR(50) NOT NULL,
  membership_type VARCHAR(32) NOT NULL CHECK (membership_type IN ('GENERAL', 'STUDENT', 'TEACHER', 'COMMITTEE', 'LIFETIME')),
  membership_date DATE NOT NULL,
  expiry_date DATE,
  max_allowed_books INT NOT NULL DEFAULT 2,
  max_issue_days INT NOT NULL DEFAULT 14,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64),
  CONSTRAINT uq_lib_member_mosque_code UNIQUE (mosque_id, member_code),
  CONSTRAINT uq_lib_member_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_lib_member_person FOREIGN KEY (mosque_id, person_id) REFERENCES person_masters(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_acquisitions (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  acquisition_number VARCHAR(64) NOT NULL,
  book_title_id VARCHAR(64) NOT NULL,
  book_title_name VARCHAR(255),
  acquisition_date DATE NOT NULL,
  source_type VARCHAR(32) NOT NULL CHECK (source_type IN ('PURCHASED', 'DONATED', 'WAQF_CONTRIBUTION', 'TRANSFERRED', 'OTHER')),
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(14, 2),
  total_cost NUMERIC(14, 2),
  supplier_name VARCHAR(255),
  donor_person_id VARCHAR(64),
  donor_name VARCHAR(255),
  expense_voucher_number VARCHAR(64),
  expense_entry_id VARCHAR(64),
  central_document_id VARCHAR(64),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  CONSTRAINT uq_book_acq_mosque_num UNIQUE (mosque_id, acquisition_number),
  CONSTRAINT uq_book_acq_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_book_acq_title FOREIGN KEY (mosque_id, book_title_id) REFERENCES book_titles(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_copies (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  book_title_id VARCHAR(64) NOT NULL,
  book_title_name VARCHAR(255),
  book_id VARCHAR(50) NOT NULL, -- e.g. "BOK-000001"
  accession_number VARCHAR(64),
  copy_number INT NOT NULL DEFAULT 1,
  room_id VARCHAR(64),
  rack_id VARCHAR(64),
  shelf_id VARCHAR(64),
  shelf_location_label VARCHAR(100),
  acquisition_id VARCHAR(64),
  condition VARCHAR(20) NOT NULL DEFAULT 'EXCELLENT' CHECK (condition IN ('NEW', 'EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED', 'CRITICAL')),
  status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'ISSUED', 'OVERDUE', 'UNDER_REPAIR', 'DAMAGED', 'LOST', 'ARCHIVED')),
  current_issue_id VARCHAR(64),
  current_holder_person_id VARCHAR(64),
  current_holder_name VARCHAR(255),
  current_holder_phone VARCHAR(32),
  purchase_price NUMERIC(14, 2),
  donor_person_id VARCHAR(64),
  donor_name VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64),
  CONSTRAINT uq_book_copy_mosque_book_id UNIQUE (mosque_id, book_id),
  CONSTRAINT uq_book_copy_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_book_copy_title FOREIGN KEY (mosque_id, book_title_id) REFERENCES book_titles(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_issues (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  issue_number VARCHAR(64) NOT NULL,
  book_copy_id VARCHAR(64) NOT NULL,
  book_id VARCHAR(50) NOT NULL,
  book_title VARCHAR(255) NOT NULL,
  member_id VARCHAR(64) NOT NULL,
  person_id VARCHAR(64) NOT NULL,
  borrower_name VARCHAR(255) NOT NULL,
  borrower_phone VARCHAR(32),
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  return_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RETURNED', 'OVERDUE', 'LOST', 'CANCELLED')),
  condition_at_issue VARCHAR(20) NOT NULL DEFAULT 'GOOD',
  condition_at_return VARCHAR(20),
  fine_amount NUMERIC(14, 2) DEFAULT 0.00,
  fine_paid BOOLEAN DEFAULT FALSE,
  fine_voucher_number VARCHAR(64),
  issued_by_user_id VARCHAR(64) NOT NULL,
  issued_by_user_name VARCHAR(255),
  returned_by_user_id VARCHAR(64),
  returned_by_user_name VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_book_issue_mosque_num UNIQUE (mosque_id, issue_number),
  CONSTRAINT uq_book_issue_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_book_issue_copy FOREIGN KEY (mosque_id, book_copy_id) REFERENCES book_copies(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_book_issue_member FOREIGN KEY (mosque_id, member_id) REFERENCES library_members(mosque_id, id) ON DELETE RESTRICT
);

-- Partial index: at most one active issue per physical book copy
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_book_copy_issue
  ON book_issues (mosque_id, book_copy_id)
  WHERE status IN ('ACTIVE', 'OVERDUE');

-- ============================================================================
-- DOMAIN B: MAKTAB OPERATIONAL RECORDS
-- ============================================================================

CREATE TABLE IF NOT EXISTS education_guardian_relationships (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  guardian_person_id VARCHAR(64) NOT NULL,
  relationship_type VARCHAR(32) NOT NULL CHECK (relationship_type IN ('FATHER', 'MOTHER', 'BROTHER', 'UNCLE', 'GRANDFATHER', 'LEGAL_GUARDIAN', 'OTHER')),
  relationship_title_bn VARCHAR(100),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_emergency_contact BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  CONSTRAINT uq_edu_guardian_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_guardian_student FOREIGN KEY (mosque_id, student_profile_id) REFERENCES education_student_profiles(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_guardian_person FOREIGN KEY (mosque_id, guardian_person_id) REFERENCES person_masters(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS maktab_classes (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  level_id VARCHAR(64) NOT NULL,
  level_code VARCHAR(50) NOT NULL,
  name_bn VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  shift VARCHAR(32) NOT NULL CHECK (shift IN ('MORNING', 'AFTERNOON', 'EVENING')),
  teacher_staff_id VARCHAR(64),
  room VARCHAR(100),
  max_capacity INT DEFAULT 30,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  CONSTRAINT uq_maktab_class_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_maktab_class_level FOREIGN KEY (mosque_id, level_id) REFERENCES education_levels(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS maktab_attendances (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  class_id VARCHAR(64),
  level_id VARCHAR(64),
  date DATE NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('PRESENT', 'ABSENT', 'LEAVE', 'LATE')),
  notes TEXT,
  recorded_by VARCHAR(64) NOT NULL,
  recorded_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_maktab_attendance_daily UNIQUE (mosque_id, student_profile_id, date),
  CONSTRAINT uq_maktab_attendance_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_maktab_att_student FOREIGN KEY (mosque_id, student_profile_id) REFERENCES education_student_profiles(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS maktab_teacher_assignments (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  staff_id VARCHAR(64) NOT NULL,
  class_id VARCHAR(64),
  level_id VARCHAR(64),
  role VARCHAR(32) NOT NULL DEFAULT 'SUBJECT_TEACHER' CHECK (role IN ('HEAD_TEACHER', 'ASSISTANT_TEACHER', 'SUBJECT_TEACHER')),
  effective_from DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  CONSTRAINT uq_maktab_teacher_assign_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_maktab_assign_staff FOREIGN KEY (mosque_id, staff_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS maktab_fee_schedules (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  title_bn VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  default_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  frequency VARCHAR(32) NOT NULL CHECK (frequency IN ('MONTHLY', 'ONE_TIME', 'YEARLY')),
  level_id VARCHAR(64),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64) NOT NULL,
  CONSTRAINT uq_maktab_fee_sched_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS maktab_fee_records (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  fee_schedule_id VARCHAR(64) NOT NULL,
  fee_title VARCHAR(255) NOT NULL,
  billing_month VARCHAR(16), -- YYYY-MM
  amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0.00),
  discount NUMERIC(14, 2) DEFAULT 0.00,
  net_payable NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  due_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('PAID', 'PARTIAL', 'UNPAID')),
  canonical_income_entry_id VARCHAR(64),
  canonical_voucher_number VARCHAR(64),
  paid_at TIMESTAMPTZ,
  payment_method VARCHAR(32),
  account_id VARCHAR(64),
  account_name VARCHAR(255),
  receipt_no VARCHAR(64),
  notes TEXT,
  collected_by VARCHAR(64),
  collected_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_maktab_fee_record_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_maktab_fee_student FOREIGN KEY (mosque_id, student_profile_id) REFERENCES education_student_profiles(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_maktab_fee_schedule FOREIGN KEY (mosque_id, fee_schedule_id) REFERENCES maktab_fee_schedules(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS maktab_student_progress (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  level_id VARCHAR(64) NOT NULL,
  level_code VARCHAR(50) NOT NULL,
  assessment_date DATE NOT NULL,
  qaida_lesson VARCHAR(255),
  ampara_surah VARCHAR(255),
  nazera_para INT,
  nazera_page INT,
  deeniyat_topic VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'NEEDS_REVISION')),
  overall_grade VARCHAR(20) NOT NULL CHECK (overall_grade IN ('A+', 'A', 'B', 'C', 'SATISFACTORY', 'NEEDS_IMPROVEMENT')),
  teacher_staff_id VARCHAR(64),
  teacher_name VARCHAR(255),
  teacher_remarks TEXT,
  next_target VARCHAR(255),
  evaluated_by VARCHAR(64) NOT NULL,
  evaluated_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_maktab_progress_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_maktab_progress_student FOREIGN KEY (mosque_id, student_profile_id) REFERENCES education_student_profiles(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_maktab_progress_level FOREIGN KEY (mosque_id, level_id) REFERENCES education_levels(mosque_id, id) ON DELETE RESTRICT
);

-- ============================================================================
-- DOMAIN C: HIFZ H2-H4 & USTAD ASSIGNMENT RECORDS
-- ============================================================================

CREATE TABLE IF NOT EXISTS hifz_sabaks (
  id VARCHAR(64) PRIMARY KEY,
  sabak_id VARCHAR(64) NOT NULL,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  date DATE NOT NULL,
  ustad_id VARCHAR(64) NOT NULL,
  ustad_name VARCHAR(255),
  start_verse_key VARCHAR(32) NOT NULL,
  end_verse_key VARCHAR(32) NOT NULL,
  total_ayahs INT NOT NULL CHECK (total_ayahs > 0),
  start_surah_number INT NOT NULL,
  start_surah_name_bn VARCHAR(100),
  end_surah_number INT NOT NULL,
  end_surah_name_bn VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'PRESENTED', 'EVALUATED', 'COMPLETED', 'CANCELLED')),
  performance VARCHAR(20) CHECK (performance IN ('EXCELLENT', 'GOOD', 'ACCEPTABLE', 'NEEDS_IMPROVEMENT', 'NOT_PASSED')),
  mistake_count INT DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_sabaks_mosque_sabak_id UNIQUE (mosque_id, sabak_id),
  CONSTRAINT uq_hifz_sabaks_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_sabak_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_sabak_ustad FOREIGN KEY (mosque_id, ustad_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS hifz_sabakis (
  id VARCHAR(64) PRIMARY KEY,
  sabaki_id VARCHAR(64) NOT NULL,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  date DATE NOT NULL,
  ustad_id VARCHAR(64) NOT NULL,
  ustad_name VARCHAR(255),
  source_sabak_id VARCHAR(64),
  source_sabak_display_id VARCHAR(64),
  start_verse_key VARCHAR(32) NOT NULL,
  end_verse_key VARCHAR(32) NOT NULL,
  total_ayahs INT NOT NULL CHECK (total_ayahs > 0),
  start_surah_number INT NOT NULL,
  start_surah_name_bn VARCHAR(100),
  end_surah_number INT NOT NULL,
  end_surah_name_bn VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'REVIEWED', 'EVALUATED', 'COMPLETED', 'CANCELLED')),
  performance VARCHAR(20) CHECK (performance IN ('EXCELLENT', 'GOOD', 'ACCEPTABLE', 'NEEDS_IMPROVEMENT', 'NOT_PASSED')),
  mistake_count INT DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_sabakis_mosque_sabaki_id UNIQUE (mosque_id, sabaki_id),
  CONSTRAINT uq_hifz_sabakis_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_sabaki_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_sabaki_ustad FOREIGN KEY (mosque_id, ustad_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS hifz_daur_cycles (
  id VARCHAR(64) PRIMARY KEY,
  cycle_id VARCHAR(64) NOT NULL,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  cycle_number INT NOT NULL DEFAULT 1,
  start_date DATE NOT NULL,
  target_end_date DATE,
  start_verse_key VARCHAR(32) NOT NULL,
  end_verse_key VARCHAR(32) NOT NULL,
  total_ayahs INT NOT NULL CHECK (total_ayahs > 0),
  start_surah_number INT NOT NULL,
  start_surah_name_bn VARCHAR(100),
  end_surah_number INT NOT NULL,
  end_surah_name_bn VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_daur_cycles_num UNIQUE (mosque_id, cycle_id),
  CONSTRAINT uq_hifz_daur_cycles_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_daur_cycle_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS hifz_daurs (
  id VARCHAR(64) PRIMARY KEY,
  daur_id VARCHAR(64) NOT NULL,
  cycle_id VARCHAR(64) NOT NULL,
  cycle_display_id VARCHAR(64),
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  date DATE NOT NULL,
  ustad_id VARCHAR(64) NOT NULL,
  ustad_name VARCHAR(255),
  start_verse_key VARCHAR(32) NOT NULL,
  end_verse_key VARCHAR(32) NOT NULL,
  total_ayahs INT NOT NULL CHECK (total_ayahs > 0),
  start_surah_number INT NOT NULL,
  start_surah_name_bn VARCHAR(100),
  end_surah_number INT NOT NULL,
  end_surah_name_bn VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'REVIEWED', 'EVALUATED', 'COMPLETED', 'CANCELLED')),
  performance VARCHAR(20) CHECK (performance IN ('EXCELLENT', 'GOOD', 'ACCEPTABLE', 'NEEDS_IMPROVEMENT', 'NOT_PASSED')),
  mistake_count INT DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_daurs_num UNIQUE (mosque_id, daur_id),
  CONSTRAINT uq_hifz_daurs_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_daur_cycle FOREIGN KEY (mosque_id, cycle_id) REFERENCES hifz_daur_cycles(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_daur_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_daur_ustad FOREIGN KEY (mosque_id, ustad_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS hifz_revisions (
  id VARCHAR(64) PRIMARY KEY,
  revision_id VARCHAR(64) NOT NULL,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  date DATE NOT NULL,
  ustad_id VARCHAR(64) NOT NULL,
  ustad_name VARCHAR(255),
  source_daur_id VARCHAR(64),
  source_daur_display_id VARCHAR(64),
  source_sabaki_id VARCHAR(64),
  source_sabaki_display_id VARCHAR(64),
  start_verse_key VARCHAR(32) NOT NULL,
  end_verse_key VARCHAR(32) NOT NULL,
  total_ayahs INT NOT NULL CHECK (total_ayahs > 0),
  start_surah_number INT NOT NULL,
  start_surah_name_bn VARCHAR(100),
  end_surah_number INT NOT NULL,
  end_surah_name_bn VARCHAR(100),
  reason VARCHAR(32) NOT NULL CHECK (reason IN ('MEMORY_WEAKNESS', 'REPEATED_MISTAKES', 'FORGOTTEN_PORTION', 'CONNECTIVITY_ISSUE', 'USTAD_ASSIGNED', 'OTHER')),
  priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'VERIFIED', 'RESOLVED', 'CANCELLED')),
  performance VARCHAR(20) CHECK (performance IN ('EXCELLENT', 'GOOD', 'ACCEPTABLE', 'NEEDS_IMPROVEMENT', 'NOT_PASSED')),
  mistake_count INT DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_revisions_num UNIQUE (mosque_id, revision_id),
  CONSTRAINT uq_hifz_revisions_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_revision_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_revision_ustad FOREIGN KEY (mosque_id, ustad_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS hifz_teacher_assignments (
  id VARCHAR(64) PRIMARY KEY,
  assignment_id VARCHAR(64) NOT NULL,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  enrollment_id VARCHAR(64) NOT NULL,
  student_profile_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255),
  ustad_staff_id VARCHAR(64) NOT NULL,
  ustad_name VARCHAR(255),
  assignment_type VARCHAR(20) NOT NULL DEFAULT 'PRIMARY' CHECK (assignment_type IN ('PRIMARY', 'SECONDARY')),
  start_date DATE NOT NULL,
  end_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ENDED', 'CANCELLED')),
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  remarks TEXT,
  assigned_by VARCHAR(64),
  assigned_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_hifz_ustad_assign_num UNIQUE (mosque_id, assignment_id),
  CONSTRAINT uq_hifz_ustad_assign_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_hifz_assign_enrollment FOREIGN KEY (mosque_id, enrollment_id) REFERENCES hifz_enrollments(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_hifz_assign_staff FOREIGN KEY (mosque_id, ustad_staff_id) REFERENCES staff(mosque_id, id) ON DELETE RESTRICT
);

-- ============================================================================
-- DOMAIN D: ASSETS / WAQF / CEMETERY
-- ============================================================================

CREATE TABLE IF NOT EXISTS mosque_assets (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  asset_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL,
  category_bn VARCHAR(100),
  brand VARCHAR(100),
  model VARCHAR(100),
  serial_number VARCHAR(100),
  purchase_date DATE NOT NULL,
  purchase_value NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  current_value NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  location VARCHAR(255) NOT NULL,
  responsible_person VARCHAR(255),
  responsible_person_phone VARCHAR(32),
  condition VARCHAR(20) NOT NULL DEFAULT 'GOOD',
  condition_bn VARCHAR(50),
  next_service_date DATE,
  warranty_info TEXT,
  supplier VARCHAR(255),
  source_of_purchase VARCHAR(255),
  notes TEXT,
  description TEXT,
  photo_url TEXT,
  attachments JSONB,
  expense_voucher_number VARCHAR(64),
  expense_entry_id VARCHAR(64),
  is_expense_linked BOOLEAN DEFAULT FALSE,
  term_id VARCHAR(64),
  term_title VARCHAR(255),
  is_archived BOOLEAN DEFAULT FALSE,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mosque_assets_mosque_code UNIQUE (mosque_id, asset_code),
  CONSTRAINT uq_mosque_assets_mosque_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS asset_service_records (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  asset_id VARCHAR(64) NOT NULL,
  service_date DATE NOT NULL,
  service_type VARCHAR(64) NOT NULL,
  service_type_bn VARCHAR(100),
  serviced_by VARCHAR(255),
  cost NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  expense_voucher_number VARCHAR(64),
  expense_entry_id VARCHAR(64),
  description TEXT NOT NULL,
  next_service_date DATE,
  performed_by VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_asset_service_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_service_asset FOREIGN KEY (mosque_id, asset_id) REFERENCES mosque_assets(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS mosque_properties (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  property_code VARCHAR(50) NOT NULL,
  name VARCHAR(255),
  name_bn VARCHAR(255),
  type VARCHAR(64) NOT NULL,
  property_type VARCHAR(64),
  category VARCHAR(64),
  description TEXT,
  location VARCHAR(255) NOT NULL,
  full_address TEXT,
  area VARCHAR(100),
  area_amount NUMERIC(12, 4),
  area_unit VARCHAR(32),
  ownership_type VARCHAR(32) NOT NULL CHECK (ownership_type IN ('WAQF', 'PURCHASED', 'DONATED', 'LEASED')),
  cs_plot_no VARCHAR(50),
  sa_plot_no VARCHAR(50),
  rs_plot_no VARCHAR(50),
  bs_plot_no VARCHAR(50),
  plot_no VARCHAR(50),
  cs_khatian_no VARCHAR(50),
  sa_khatian_no VARCHAR(50),
  rs_khatian_no VARCHAR(50),
  bs_khatian_no VARCHAR(50),
  mutation_khatian_no VARCHAR(50),
  khatian_no VARCHAR(50),
  mouza VARCHAR(100),
  jl_number VARCHAR(50),
  sub_registry_office VARCHAR(100),
  boundary_north TEXT,
  boundary_south TEXT,
  boundary_east TEXT,
  boundary_west TEXT,
  waqf_enrollment_no VARCHAR(100),
  waqf_deed_no VARCHAR(100),
  waqf_year VARCHAR(32),
  waqf_deed_date DATE,
  waqf_ec_number VARCHAR(100),
  waqif_name VARCHAR(255),
  waqif_father_name VARCHAR(255),
  waqif_address TEXT,
  waqf_purpose TEXT,
  waqf_estate_name VARCHAR(255),
  current_use TEXT,
  possession_status VARCHAR(32),
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  estimated_value NUMERIC(14, 2),
  monthly_income NUMERIC(14, 2),
  monthly_rent NUMERIC(14, 2),
  annual_income NUMERIC(14, 2),
  photo_url TEXT,
  is_archived BOOLEAN DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mosque_properties_code UNIQUE (mosque_id, property_code),
  CONSTRAINT uq_mosque_properties_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS property_tenants (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  property_id VARCHAR(64) NOT NULL,
  tenant_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  father_or_spouse_name VARCHAR(255),
  mobile VARCHAR(32) NOT NULL,
  nid VARCHAR(50),
  address TEXT,
  photo_url TEXT,
  unit_or_shop_no VARCHAR(100),
  business_name VARCHAR(255),
  business_type VARCHAR(100),
  agreement_no VARCHAR(100),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  monthly_rent NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  annual_rent NUMERIC(14, 2),
  security_deposit NUMERIC(14, 2) DEFAULT 0.00,
  payment_due_date INT DEFAULT 10,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'TERMINATED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_property_tenant_code UNIQUE (mosque_id, tenant_code),
  CONSTRAINT uq_property_tenant_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_tenant_property FOREIGN KEY (mosque_id, property_id) REFERENCES mosque_properties(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS property_rent_collections (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  property_id VARCHAR(64) NOT NULL,
  property_code VARCHAR(50),
  property_name VARCHAR(255),
  tenant_id VARCHAR(64) NOT NULL,
  tenant_name VARCHAR(255) NOT NULL,
  tenant_code VARCHAR(50),
  shop_or_unit_no VARCHAR(100),
  billing_month VARCHAR(16) NOT NULL, -- YYYY-MM
  monthly_rent NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  previous_due NUMERIC(14, 2) DEFAULT 0.00,
  total_due NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  paid_amount NUMERIC(14, 2) NOT NULL CHECK (paid_amount > 0.00),
  remaining_due NUMERIC(14, 2) DEFAULT 0.00,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(32) NOT NULL,
  account_id VARCHAR(64),
  account_name VARCHAR(255),
  receipt_number VARCHAR(64) NOT NULL,
  income_voucher_number VARCHAR(64),
  income_entry_id VARCHAR(64),
  is_accounting_linked BOOLEAN DEFAULT FALSE,
  collector_name VARCHAR(255),
  collector_designation VARCHAR(100),
  denomination_data JSONB,
  notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PAID' CHECK (status IN ('PAID', 'PARTIAL', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_rent_coll_mosque_rcpt UNIQUE (mosque_id, receipt_number),
  CONSTRAINT uq_rent_coll_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_rent_coll_property FOREIGN KEY (mosque_id, property_id) REFERENCES mosque_properties(mosque_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_rent_coll_tenant FOREIGN KEY (mosque_id, tenant_id) REFERENCES property_tenants(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS property_documents (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  property_id VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  document_type VARCHAR(64) NOT NULL,
  document_type_bn VARCHAR(100),
  issue_date DATE,
  description TEXT,
  file_url TEXT NOT NULL,
  file_name VARCHAR(255),
  file_size INT,
  uploaded_by VARCHAR(64),
  uploaded_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_property_docs_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_prop_doc_property FOREIGN KEY (mosque_id, property_id) REFERENCES mosque_properties(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS property_khajna_records (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  property_id VARCHAR(64) NOT NULL,
  tax_year VARCHAR(64) NOT NULL,
  amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0.00),
  payment_date DATE NOT NULL,
  receipt_number VARCHAR(100) NOT NULL,
  next_due_date DATE,
  holding_no VARCHAR(100),
  paid_to_office VARCHAR(255),
  document_url TEXT,
  notes TEXT,
  expense_voucher_number VARCHAR(64),
  expense_entry_id VARCHAR(64),
  is_expense_linked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_property_khajna_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_khajna_property FOREIGN KEY (mosque_id, property_id) REFERENCES mosque_properties(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS cemetery_records (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  record_number VARCHAR(64),
  plot_number VARCHAR(50) NOT NULL,
  block VARCHAR(50),
  block_name VARCHAR(100),
  row VARCHAR(50),
  row_number VARCHAR(50),
  grave_location VARCHAR(255) NOT NULL,
  grave_type VARCHAR(32) DEFAULT 'GENERAL',
  plot_status VARCHAR(32) NOT NULL DEFAULT 'OCCUPIED',
  status VARCHAR(32),
  deceased_name VARCHAR(255) NOT NULL,
  deceased_name_bn VARCHAR(255),
  father_or_spouse_name VARCHAR(255) NOT NULL,
  father_name VARCHAR(255),
  mother_name VARCHAR(255),
  husband_or_spouse_name VARCHAR(255),
  gender VARCHAR(16),
  date_of_birth DATE,
  age VARCHAR(32),
  age_at_death VARCHAR(32),
  date_of_death DATE NOT NULL,
  cause_of_death VARCHAR(255),
  religion VARCHAR(64) DEFAULT 'Islam',
  graveyard_name VARCHAR(255),
  burial_date DATE NOT NULL,
  burial_time VARCHAR(32),
  janaza_place VARCHAR(255),
  contact_person_name VARCHAR(255) NOT NULL,
  contact_person_phone VARCHAR(32) NOT NULL,
  contact_person_alt_phone VARCHAR(32),
  relation_with_deceased VARCHAR(100),
  contact_relationship VARCHAR(100),
  heir_address TEXT,
  heirs JSONB,
  burial_fee NUMERIC(14, 2) DEFAULT 0.00,
  maintenance_fee NUMERIC(14, 2) DEFAULT 0.00,
  donation_amount NUMERIC(14, 2) DEFAULT 0.00,
  donation_voucher_no VARCHAR(64),
  donation_entry_id VARCHAR(64),
  donation_payment_method VARCHAR(32),
  donation_account_id VARCHAR(64),
  maintenance_logs JSONB,
  notes TEXT,
  is_archived BOOLEAN DEFAULT FALSE,
  archived_at TIMESTAMPTZ,
  archived_by VARCHAR(64),
  archived_by_name VARCHAR(255),
  archive_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by VARCHAR(64),
  updated_by_name VARCHAR(255),
  CONSTRAINT uq_cemetery_records_id UNIQUE (mosque_id, id)
);

-- ============================================================================
-- DOMAIN E: COMMITTEE GOVERNANCE EXTENDED
-- ============================================================================

CREATE TABLE IF NOT EXISTS committee_meeting_notices (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  memo_no VARCHAR(100) NOT NULL,
  serial_number VARCHAR(50),
  notice_date DATE NOT NULL,
  meeting_date DATE NOT NULL,
  day_name VARCHAR(32),
  time VARCHAR(32),
  venue VARCHAR(255),
  meeting_type VARCHAR(64),
  meeting_type_bn VARCHAR(100),
  agendas TEXT[],
  remarks TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'ISSUED' CHECK (status IN ('ISSUED', 'CONVERTED_TO_MINUTES', 'CANCELLED')),
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comm_meeting_notices_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS committee_meetings (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  term_id VARCHAR(64),
  term_title VARCHAR(255),
  meeting_number VARCHAR(50) NOT NULL,
  document_number VARCHAR(100),
  memo_number VARCHAR(100),
  date DATE NOT NULL,
  time VARCHAR(32),
  day_name VARCHAR(32),
  meeting_type VARCHAR(64) DEFAULT 'GENERAL',
  meeting_type_bn VARCHAR(100),
  venue VARCHAR(255),
  chairman VARCHAR(255),
  secretary VARCHAR(255),
  conductor VARCHAR(255),
  subject VARCHAR(255),
  agendas JSONB,
  attendees JSONB,
  decisions JSONB,
  assigned_tasks JSONB,
  revisions JSONB,
  status VARCHAR(20) NOT NULL DEFAULT 'FINAL' CHECK (status IN ('DRAFT', 'FINAL', 'REVISED', 'CANCELLED')),
  notes TEXT,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_committee_meetings_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS meeting_resolutions (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  resolution_number VARCHAR(100) NOT NULL,
  resolution_type VARCHAR(32) DEFAULT 'INDIVIDUAL' CHECK (resolution_type IN ('INDIVIDUAL', 'COMBINED')),
  meeting_id VARCHAR(64) NOT NULL,
  meeting_document_number VARCHAR(100),
  meeting_number VARCHAR(50),
  meeting_date DATE,
  date DATE NOT NULL,
  subject VARCHAR(255) NOT NULL,
  background TEXT,
  consideration TEXT,
  proposal TEXT,
  proposer_name VARCHAR(255),
  supporter_name VARCHAR(255),
  resolution_text TEXT NOT NULL,
  assigned_member_id VARCHAR(64),
  assigned_member_name VARCHAR(255),
  assigned_member_designation VARCHAR(100),
  assigned_member_phone VARCHAR(32),
  task_description TEXT,
  deadline DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'APPROVED' CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'CANCELLED')),
  priority VARCHAR(20) DEFAULT 'NORMAL' CHECK (priority IN ('NORMAL', 'HIGH', 'URGENT')),
  implementation_status VARCHAR(20) DEFAULT 'PENDING' CHECK (implementation_status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'CANCELLED')),
  progress_percentage INT DEFAULT 0,
  completion_date DATE,
  financial_amount NUMERIC(14, 2),
  term_id VARCHAR(64),
  term_title VARCHAR(255),
  remarks TEXT,
  president_signature_url TEXT,
  secretary_signature_url TEXT,
  is_revised BOOLEAN DEFAULT FALSE,
  revision_number INT DEFAULT 0,
  revision_reason TEXT,
  revision_history JSONB,
  items JSONB,
  audit_logs JSONB,
  created_by VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meeting_res_mosque_num UNIQUE (mosque_id, resolution_number),
  CONSTRAINT uq_meeting_res_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_resolution_meeting FOREIGN KEY (mosque_id, meeting_id) REFERENCES committee_meetings(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sub_committees (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  sub_committee_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  term_id VARCHAR(64) NOT NULL,
  term_title VARCHAR(255),
  formation_date DATE NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'DISSOLVED', 'INACTIVE', 'ARCHIVED')),
  convener_id VARCHAR(64),
  convener_name VARCHAR(255) NOT NULL,
  convener_phone VARCHAR(32),
  secretary_id VARCHAR(64),
  secretary_name VARCHAR(255),
  secretary_phone VARCHAR(32),
  member_ids TEXT[],
  members JSONB,
  scope_of_work TEXT NOT NULL,
  duties TEXT NOT NULL,
  notes TEXT,
  resolution_id VARCHAR(64),
  resolution_number VARCHAR(100),
  resolution_subject VARCHAR(255),
  progress_percentage INT DEFAULT 0,
  target_deliverables TEXT,
  activity_logs JSONB,
  member_history JSONB,
  is_archived BOOLEAN DEFAULT FALSE,
  created_by VARCHAR(64),
  created_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sub_committees_mosque_code UNIQUE (mosque_id, sub_committee_code),
  CONSTRAINT uq_sub_committees_mosque_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_sub_committee_term FOREIGN KEY (mosque_id, term_id) REFERENCES committee_terms(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS committee_action_plans (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  plan_number VARCHAR(50) NOT NULL,
  term_id VARCHAR(64) NOT NULL,
  term_title VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('URGENT', 'HIGH', 'MEDIUM', 'NORMAL')),
  responsible_member_id VARCHAR(64),
  responsible_member_name VARCHAR(255),
  responsible_member_designation VARCHAR(100),
  responsible_member_phone VARCHAR(32),
  responsible_member_ids TEXT[],
  responsible_members JSONB,
  assistant_member_ids TEXT[],
  assistant_members JSONB,
  sub_committee_id VARCHAR(64),
  sub_committee_name VARCHAR(255),
  start_date DATE NOT NULL,
  due_date DATE NOT NULL,
  completed_date DATE,
  estimated_budget NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  actual_cost NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  funding_source VARCHAR(255),
  funding_account_id VARCHAR(64),
  funding_account_name VARCHAR(255),
  financial_voucher_number VARCHAR(64),
  status VARCHAR(20) NOT NULL DEFAULT 'TODO' CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED')),
  progress_percentage INT NOT NULL DEFAULT 0,
  remarks TEXT,
  resolution_id VARCHAR(64),
  resolution_number VARCHAR(100),
  resolution_subject VARCHAR(255),
  meeting_id VARCHAR(64),
  meeting_number VARCHAR(50),
  decision_number VARCHAR(50),
  attachments JSONB,
  activity_logs JSONB,
  is_archived BOOLEAN DEFAULT FALSE,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_by VARCHAR(64) NOT NULL,
  created_by_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comm_action_plans_code UNIQUE (mosque_id, plan_number),
  CONSTRAINT uq_comm_action_plans_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_action_plan_term FOREIGN KEY (mosque_id, term_id) REFERENCES committee_terms(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS committee_member_activities (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  member_id VARCHAR(64) NOT NULL,
  term_id VARCHAR(64),
  activity_type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date DATE NOT NULL,
  hours_spent NUMERIC(6, 2) DEFAULT 0.00,
  cost_incurred NUMERIC(14, 2) DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comm_activities_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_activity_member FOREIGN KEY (mosque_id, member_id) REFERENCES committee_members(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS committee_member_tasks (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  member_id VARCHAR(64) NOT NULL,
  action_plan_id VARCHAR(64),
  meeting_id VARCHAR(64),
  title VARCHAR(255) NOT NULL,
  task_description TEXT,
  priority VARCHAR(20) DEFAULT 'NORMAL',
  start_date DATE,
  due_date DATE,
  completed_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  progress_percentage INT DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comm_tasks_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_task_member FOREIGN KEY (mosque_id, member_id) REFERENCES committee_members(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS committee_manual_evaluations (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  member_id VARCHAR(64) NOT NULL,
  term_id VARCHAR(64) NOT NULL,
  evaluation_year INT NOT NULL,
  score NUMERIC(5, 2) NOT NULL,
  evaluation_grade VARCHAR(10),
  feedback TEXT,
  evaluated_by VARCHAR(64) NOT NULL,
  evaluated_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_comm_eval_member_year UNIQUE (mosque_id, member_id, evaluation_year),
  CONSTRAINT uq_comm_eval_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_eval_member FOREIGN KEY (mosque_id, member_id) REFERENCES committee_members(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS advisory_council_terms (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'HISTORICAL')),
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_advisory_terms_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS advisor_members (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  term_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  father_name VARCHAR(255),
  mother_name VARCHAR(255),
  nid VARCHAR(50),
  phone VARCHAR(32) NOT NULL,
  alt_phone VARCHAR(32),
  date_of_birth DATE,
  blood_group VARCHAR(16),
  address TEXT,
  photo_url TEXT,
  advisor_role VARCHAR(100) DEFAULT 'উপদেষ্টা',
  occupation VARCHAR(100),
  education VARCHAR(100),
  email VARCHAR(128),
  join_date DATE NOT NULL,
  end_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'RESIGNED', 'DECEASED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_advisor_members_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_advisor_term FOREIGN KEY (mosque_id, term_id) REFERENCES advisory_council_terms(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS advisor_consultations (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  advisor_id VARCHAR(64),
  advisor_name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  topic VARCHAR(255) NOT NULL,
  advice TEXT NOT NULL,
  related_context TEXT,
  impact_outcome TEXT,
  status VARCHAR(20) DEFAULT 'RECORDED' CHECK (status IN ('RECORDED', 'REVIEWED', 'ACCEPTED', 'IMPLEMENTED')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_advisor_consult_id UNIQUE (mosque_id, id)
);

-- ============================================================================
-- DOMAIN F: FINANCIAL PLANNING / FIELD COLLECTION
-- ============================================================================

CREATE TABLE IF NOT EXISTS budgets (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  budget_name VARCHAR(255) NOT NULL,
  budget_type VARCHAR(32) NOT NULL CHECK (budget_type IN ('OPERATING', 'PROJECT')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'ACTIVE', 'REVISED', 'CLOSED')),
  notes TEXT,
  total_planned_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  revision_number INT NOT NULL DEFAULT 1,
  previous_revision_id VARCHAR(64),
  project_id VARCHAR(64),
  created_by VARCHAR(64) NOT NULL,
  created_by_name VARCHAR(255),
  approved_by VARCHAR(64),
  approved_by_name VARCHAR(255),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_archived BOOLEAN DEFAULT FALSE,
  CONSTRAINT uq_budgets_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS budget_lines (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  budget_id VARCHAR(64) NOT NULL,
  main_head_id VARCHAR(64) NOT NULL,
  main_head_name_bn VARCHAR(255) NOT NULL,
  sub_head_id VARCHAR(64),
  sub_head_name_bn VARCHAR(255),
  planned_amount NUMERIC(14, 2) NOT NULL CHECK (planned_amount >= 0.00),
  notes TEXT,
  CONSTRAINT uq_budget_lines_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_budget_line_budget FOREIGN KEY (mosque_id, budget_id) REFERENCES budgets(mosque_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_budget_line_head FOREIGN KEY (mosque_id, main_head_id) REFERENCES account_heads(mosque_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS donation_plans (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  plan_code VARCHAR(50),
  target_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  collected_amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
  start_date DATE NOT NULL,
  end_date DATE,
  category VARCHAR(64) NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by VARCHAR(64),
  CONSTRAINT uq_donation_plans_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS collection_workers (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  worker_code VARCHAR(50) NOT NULL,
  person_id VARCHAR(64),
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  address TEXT,
  assigned_area_ids TEXT[],
  commission_percentage NUMERIC(5, 2) DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_coll_worker_mosque_code UNIQUE (mosque_id, worker_code),
  CONSTRAINT uq_coll_worker_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS donation_collections (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  collection_number VARCHAR(64) NOT NULL,
  collection_date DATE NOT NULL,
  worker_id VARCHAR(64),
  worker_name VARCHAR(255),
  area_id VARCHAR(64),
  donation_plan_id VARCHAR(64),
  amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0.00),
  payment_method VARCHAR(32) NOT NULL,
  account_id VARCHAR(64) NOT NULL,
  account_name VARCHAR(255) NOT NULL,
  income_voucher_number VARCHAR(64),
  income_entry_id VARCHAR(64),
  donor_count INT DEFAULT 1,
  notes TEXT,
  created_by VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_don_coll_mosque_num UNIQUE (mosque_id, collection_number),
  CONSTRAINT uq_don_coll_id UNIQUE (mosque_id, id),
  CONSTRAINT fk_don_coll_account FOREIGN KEY (mosque_id, account_id) REFERENCES financial_accounts(mosque_id, id) ON DELETE RESTRICT
);

-- ============================================================================
-- DOMAIN G: DOCUMENT MANAGEMENT & COMMUNICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS central_documents (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  entity_type VARCHAR(64) NOT NULL,
  entity_id VARCHAR(64) NOT NULL,
  entity_title VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  original_file_name VARCHAR(255),
  file_url TEXT,
  file_type VARCHAR(64),
  file_size INT,
  google_drive_url TEXT,
  document_date DATE,
  document_type VARCHAR(64) NOT NULL,
  document_type_bn VARCHAR(100),
  description TEXT,
  visibility VARCHAR(20) NOT NULL DEFAULT 'RESTRICTED' CHECK (visibility IN ('PRIVATE', 'RESTRICTED', 'PUBLIC')),
  version INT DEFAULT 1,
  uploaded_by VARCHAR(64) NOT NULL,
  uploaded_by_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_central_docs_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS official_documents (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  document_number VARCHAR(100) NOT NULL,
  template_id VARCHAR(64),
  title VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL,
  issue_date DATE NOT NULL,
  recipient_name VARCHAR(255),
  recipient_address TEXT,
  subject VARCHAR(255) NOT NULL,
  body_content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ISSUED' CHECK (status IN ('DRAFT', 'ISSUED', 'CANCELLED', 'ARCHIVED')),
  signatory_name VARCHAR(255),
  signatory_designation VARCHAR(100),
  signature_url TEXT,
  central_document_id VARCHAR(64),
  created_by VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_official_docs_num UNIQUE (mosque_id, document_number),
  CONSTRAINT uq_official_docs_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS official_document_templates (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  template_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL,
  default_subject VARCHAR(255),
  template_body TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_official_doc_tpl_code UNIQUE (mosque_id, template_code),
  CONSTRAINT uq_official_doc_tpl_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS public_document_tokens (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  document_id VARCHAR(64) NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  is_revoked BOOLEAN DEFAULT FALSE,
  access_count INT DEFAULT 0,
  last_accessed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_pub_doc_tokens_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS mosque_notices (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  publish_date DATE NOT NULL,
  expiry_date DATE,
  priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DRAFT')),
  published_by VARCHAR(64) NOT NULL,
  published_by_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mosque_notices_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS mosque_notifications (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  user_id VARCHAR(64),
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(32) NOT NULL DEFAULT 'INFO' CHECK (type IN ('INFO', 'SUCCESS', 'WARNING', 'ALERT', 'TRANSACTION')),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  link TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mosque_notifications_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS sms_logs (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  recipient_phone VARCHAR(32) NOT NULL,
  recipient_name VARCHAR(255),
  message TEXT NOT NULL,
  gateway_status VARCHAR(32),
  status VARCHAR(20) NOT NULL DEFAULT 'SENT' CHECK (status IN ('SENT', 'FAILED', 'PENDING')),
  sent_by VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sms_logs_id UNIQUE (mosque_id, id)
);

CREATE TABLE IF NOT EXISTS uploaded_files (
  id VARCHAR(64) PRIMARY KEY,
  mosque_id VARCHAR(64) NOT NULL REFERENCES mosques(id) ON DELETE RESTRICT,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(64) NOT NULL,
  file_size INT NOT NULL,
  url TEXT NOT NULL,
  uploaded_by VARCHAR(64) NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_uploaded_files_id UNIQUE (mosque_id, id)
);

-- ============================================================================
-- AUXILIARY INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_book_copies_title ON book_copies (mosque_id, book_title_id);
CREATE INDEX IF NOT EXISTS idx_book_issues_member ON book_issues (mosque_id, member_id);
CREATE INDEX IF NOT EXISTS idx_maktab_att_date ON maktab_attendances (mosque_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_hifz_sabaks_student ON hifz_sabaks (mosque_id, student_profile_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_hifz_sabakis_student ON hifz_sabakis (mosque_id, student_profile_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_hifz_daurs_student ON hifz_daurs (mosque_id, student_profile_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_mosque_assets_cat ON mosque_assets (mosque_id, category);
CREATE INDEX IF NOT EXISTS idx_central_docs_entity ON central_documents (mosque_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_budget_lines_budget ON budget_lines (mosque_id, budget_id);
`;
